CREATE TABLE users
(
    id BIGSERIAL PRIMARY KEY,
    oidc_sub VARCHAR(100) NOT NULL,
    given_name VARCHAR(100) NOT NULL,
    family_name VARCHAR(100) NOT NULL,
    email  VARCHAR(150) NOT NULL,
    picture  VARCHAR(150) NOT NULL
    last_login TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_id ON users(id);